Notify Github about wimpy deployments
wimpy/wimpy.deploy pull request #15
Opened 2017-03-08 16:01 UTC by fiunchinho

The deployments should now appear on the Pull request information on Github UI.

This only covers the happy path for now. If we think it's interesting, we can try to cover when deployments fail

2017-03-08 16:33 UTC, fiunchinho commented
@Hyunk3l @aramirez-es @ismFerDev

2017-03-08 17:39 UTC, Hyunk3l approved these changes
👏 😄 👍

2017-03-08 17:39 UTC, Hyunk3l commented on defaults/main.yml
> +github_api: "{{ ( github_host == 'github.com' ) | ternary('https://api.github.com','https://' ~ github_host ~ '/api/v3') }}"
should cover both github.com and ghe, right?

2017-03-08 17:39 UTC, Hyunk3l commented on defaults/main.yml
> +github_proto: "{{ github_url_parts[0] | default('') | regex_replace(':', '') }}"
unused, right?

2017-03-08 17:39 UTC, Hyunk3l commented on tasks/deploy.yml
> +- include: notify.yml
No way to avoid it, right?

2017-03-08 17:55 UTC, fiunchinho commented on defaults/main.yml
> +github_api: "{{ ( github_host == 'github.com' ) | ternary('https://api.github.com','https://' ~ github_host ~ '/api/v3') }}"
Yes, I've tested and it seemed to work

2017-03-08 17:55 UTC, fiunchinho commented on tasks/deploy.yml
> +- include: notify.yml
What do you mean? The task inside `notify.yml` won't be executed if the github project is not passed as parameter

2017-03-08 17:57 UTC, fiunchinho commented on defaults/main.yml
> +github_proto: "{{ github_url_parts[0] | default('') | regex_replace(':', '') }}"
You are right. FIxed!

2017-03-08 17:57 UTC, Hyunk3l commented on tasks/deploy.yml
> +- include: notify.yml
I didn't see `when: wimpy_github_project_url != ''` xD sorry!

2017-03-08 18:34 UTC, ismaelfernandezscmspain reviewed
nice PR and be druid

2017-03-09 07:26 UTC, aramirez-es commented on defaults/main.yml
> +# Github
Is this an Ansible's module?
If not, don't you should use `wimpy_` prefix?

2017-03-09 07:34 UTC, aramirez-es commented
It seems very interesting but I'm worry about what happens if the notification to GH fails. I mean, Ansible will output error if either of notification tasks fail. 

We can ignore those errors so that the output will success even notification cannot be performed.

What do you think guys?

2017-03-09 07:56 UTC, ismaelfernandezscmspain commented
mmmm... when can GH notification fail?
- GH down
- URL malformed
- Wrong credentials
...
I think that the job must fail if notification fails, then you will have to review why

2017-03-09 10:38 UTC, fiunchinho commented
Maybe it's probably better to ignore the notification error, otherwise, we could get an error even though the application was correctly deployed.

2017-03-09 14:31 UTC, aramirez-es requested changes
Please, prefix `github` vars with `wimpy_` and ignore fails publishing statuses to GH.

2017-03-12 13:58 UTC, fiunchinho commented on tasks/create_github_deployment.yml
> +    when: wimpy_github_deployment_out|succeeded
Ignoring errors and executing only if the task creating the deployment succeeded

2017-03-12 13:58 UTC, fiunchinho commented
Fixed! Please, @aramirez-es take a look

2017-03-12 14:19 UTC, fiunchinho commented
Also, I rebased from master

2017-03-12 15:12 UTC, aramirez-es approved these changes

2017-03-12 15:58 UTC, merged