Allow attach SSL certificate to ELB listeners
wimpy/wimpy.deploy pull request #76
Opened 2017-10-03 07:59 UTC by aramirez-es

With this PR, it's possible to attach SSL certificate to ELB listeners.

2017-10-03 08:32 UTC, fiunchinho approved these changes
I dont really know how these conditions work, but it looks correct

2017-10-04 09:09 UTC, ismferd requested changes
@aramirez-es, Where do you inform the value for `ssl_certificate_id` to cloudformation ?

2017-10-04 13:48 UTC, aramirez-es commented
@ismFerDev you can set `ssl_certificate_id` as a listener property, you can check it in the README. It's an optional var.

2017-10-04 14:15 UTC, ismferd approved these changes

2017-10-04 16:09 UTC, merged